old/old/old/config/routes.rb
Rails.application.routes.draw do
get 'websites/new', to: 'websites#new', as: :new_website
get 'websites/create' 
get 'websites/delete' 

root :to => "websites#new"



end

old/old/old/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

old/old/old/app/models/website.rb
class Website < ApplicationRecord

def self.looping

require 'open-uri'
Website.all.each do |p|
  if p.url
  	k=p.url+'/'
  url = URI.parse(p.url)
  # `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`
  open(url)
end
  
end


end


def rectify
	k="https://"
@test_string= self.url
if @test_string["http://www."]
   @test_string.slice! "http://www."
   @test_string = k+@test_string

elsif @test_string["https://www."]
@test_string.slice! "https://www."
@test_string = k+@test_string

elsif  @test_string["http://"]
   @test_string.slice! "http://"
   @test_string=k+@test_string

elsif @test_string["https://"]


elsif @test_string["www."]
   @test_string.slice! "www."
@test_string = k+@test_string


else
	@test_string = k+@test_string

end

self.url=@test_string
end


end

old/old/old/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

old/old/old/app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  

  def new
  end


  def create
   @w=params[:url]
   @email=params[:email]
@website = Website.new
@website.url=@w
@website.email=@email

if !( Website.exists?(url: @website.rectify ) and  Website.exists?(email: @email))  
@website.save
  render json: {}, status: 200
else
      render json: {}, status: 400
    end
end










def delete
   @w=Website.new
@w.url=params[:url]
   @email=params[:email]
@website = Website.where(email: @email)
c=0
@website.each do |p|
  if p.url == @w.rectify
    c=c+1
    p.destroy
  end
end
if(c!=0) 
    render json: {}, status: 200
   else
   render json:{},status: 400 
    
end
end


















end

old/old/old/app/helpers/application_helper.rb
module ApplicationHelper
end

old/old/old/app/helpers/websites_helper.rb
module WebsitesHelper
end

old/old/old/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link rel="shortcut icon" href="/assets/icon.png" /> 

  	 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HerokuOnCaffeine</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>











  <body>
  	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

old/old/old/app/views/websites/_form.html.erb
<%= form_for (website), remote: true  do |f| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url, "Website"%>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit "Submit"%>
  </div>
<% end %>

old/old/old/app/views/websites/create.js.erb
alert("dome");

old/old/old/app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

old/old/old/app/views/websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Websites</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.url %></td>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path %>

old/old/old/app/views/websites/new.html.erb
  <head>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
 

    <style type="text/css">
      .form-group {
  position: relative;
  /*margin-bottom: 1.5rem;*/
}

.form-control-placeholder {
  position: absolute;
  top: 0;
  padding: 7px 0 0 13px;
  transition: all 200ms;
  opacity: 0.5;
}

.form-control:focus + .form-control-placeholder,
.form-control:valid + .form-control-placeholder {
  font-size: 75%;
  transform: translate3d(0, -100%, 0);
  opacity: 1;
}
body {
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
}
#scroll {
  position: absolute;
  width: 100%;
  height: 100%;
  overflow: auto;
}
.page {
  width: 100%;
  height: 100vh;
}

    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8, shrink-to-fit=yes">
  </head>
  <body>	  

  	    	<div id="scroll">
<div class="container my-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
    	<div class="page" id="one">
    <center>
    <img width=450 height=450 src="/assets/Skull_and_Crossbones.svg" />


</center> 
<br>
<br>




      <div class="form-group">
        <input type="text" id="caffeinate" class="form-control" required>
        <label class="form-control-placeholder" for="name">Caffeinate</label>
      </div>

<div class="form-group">
        <input type="text" id="email" class="form-control" required>
        <label class="form-control-placeholder" for="name">E-mail</label>
      </div>

<center><button type="button" class="btn btn-outline-danger btn-lg" onclick="smit()">Caffeinate</button></center>
</div>
  <div class="page" id="two">


    <center><img width=450 height=450 src="/assets/for-cross-clipart-black-and-white.jpg" /></center>
    <br>
    <br>
    <br>


      <div class="form-group">
        <input type="text" id="decaffeinate" class="form-control" required>
        <label class="form-control-placeholder" for="password">De-Caffeinate</label>
      </div>
      <div class="form-group">
        <input type="text" id="deemail" class="form-control" required>
        <label class="form-control-placeholder" for="name">E-mail</label>
      </div>
      <center><button type="button" class="btn btn-outline-success btn-lg" onclick="smit2()">De-Caffeinate</button></center>
</div>
    </div>
  </div>
</div>
</div>
</div>
</body>

<script type="text/javascript">
    document.getElementById("caffeinate").addEventListener("click", function(event){
  event.preventDefault()
  
});
  document.getElementById("decaffeinate").addEventListener("click", function(event){
  event.preventDefault()
});
  function ValidateEmail(mail) 
{
 

 var mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
 if(mail.match(mailformat))
  {
    return (true)
  }
    
    return (false)
}

function removeBack(mail){
var lastChar=mail[mail.length -1];
if(lastChar=='/')
{
mail=mail.substring(0,mail.length - 1);

}
return mail;
}


function validateWebsite(mail) 
{
 

 var mailformat = /^((https?|ftp|smtp):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$/;

 if(mail.match(mailformat))
  {
    return (true)
  }
    
    return (false)
}

function  smit(){


var wp=document.getElementById("caffeinate").value;
var wt=document.getElementById("email").value;
wp=removeBack(wp);

if(validateWebsite(wp) && ValidateEmail(wt))
$.ajax({
  type:"GET",
  url:"websites/create",
  dataType:"json",
  data: { url: wp,email: wt},
  success:function(result){
Swal.fire(
  'Good job!',
  'Website is Successfully Caffeinated!',
  'success'
) 
wp="";
wt="";

 },
      error: function () {
Swal.fire({
  type: 'error',
  title: 'Oops...',
  text: 'Details exists!'
})      }
})



else
{
Swal.fire({
  type: 'error',
  title: 'Oops...',
  text: 'Details not Entered!'
})
}
}



function  smit2(){


var wp=document.getElementById("decaffeinate").value;
var wt=document.getElementById("deemail").value;
wp=removeBack(wp);

if(validateWebsite(wp) && ValidateEmail(wt))
$.ajax({
  type:"GET",
  url:"websites/delete",
  dataType:"json",
  data: { url: wp,email: wt},
  success:function(result){
Swal.fire(
  'Good job!',
  'Website is Successfully De-Caffeinated!',
  'success'
) 
wp="";
wt="";

 },
      error: function () {
Swal.fire({
  type: 'error',
  title: 'Oops...',
  text: 'Details not Found!'
})      }
})



else
{
Swal.fire({
  type: 'error',
  title: 'Oops...',
  text: 'Details are Incorrect!'
})
}
}


</script>
<script type="text/javascript">
	


/* See related post at
https://codepen.io/Javarome/post/full-page-sliding
*/
function ScrollHandler(pageId) {
  var page = document.getElementById(pageId);
  var pageStart = page.offsetTop;
  var pageJump = false;
  var viewStart;
  var duration = 1000;
  var scrolled = document.getElementById("scroll");

  function scrollToPage() {
    pageJump = true;

    // Calculate how far to scroll
    var startLocation = viewStart;
    var endLocation = pageStart;
    var distance = endLocation - startLocation;

    var runAnimation;

    // Set the animation variables to 0/undefined.
    var timeLapsed = 0;
    var percentage, position;

    var easing = function(progress) {
      return progress < 0.5
        ? 4 * progress * progress * progress
        : (progress - 1) * (2 * progress - 2) * (2 * progress - 2) + 1; // acceleration until halfway, then deceleration
    };

    function stopAnimationIfRequired(pos) {
      if (pos == endLocation) {
        cancelAnimationFrame(runAnimation);
        setTimeout(function() {
          pageJump = false;
        }, 500);
      }
    }

    var animate = function() {
      timeLapsed += 16;
      percentage = timeLapsed / duration;
      if (percentage > 1) {
        percentage = 1;
        position = endLocation;
      } else {
        position = startLocation + distance * easing(percentage);
      }
      scrolled.scrollTop = position;
      runAnimation = requestAnimationFrame(animate);
      stopAnimationIfRequired(position);
      console.log("position=" + scrolled.scrollTop + "(" + percentage + ")");
    };
    // Loop the animation function
    runAnimation = requestAnimationFrame(animate);
  }

  window.addEventListener("wheel", function(event) {
    viewStart = scrolled.scrollTop;
    if (!pageJump) {
      var pageHeight = page.scrollHeight;
      var pageStopPortion = pageHeight / 2;
      var viewHeight = window.innerHeight;

      var viewEnd = viewStart + viewHeight;
      var pageStartPart = viewEnd - pageStart;
      var pageEndPart = pageStart + pageHeight - viewStart;

      var canJumpDown = pageStartPart >= 0;
      var stopJumpDown = pageStartPart > pageStopPortion;

      var canJumpUp = pageEndPart >= 0;
      var stopJumpUp = pageEndPart > pageStopPortion;

      var scrollingForward = event.deltaY > 0;
      if (
        (scrollingForward && canJumpDown && !stopJumpDown) ||
        (!scrollingForward && canJumpUp && !stopJumpUp)
      ) {
        event.preventDefault();
        scrollToPage();
      }
      false; //
    } else {
      event.preventDefault();
    }
  });
}
new ScrollHandler("one");
new ScrollHandler("two");






</script>

old/old/old/app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>